KERNEL_SOURCE=https://github.com/MiCode/Xiaomi_Kernel_OpenSource
KERNEL_SOURCE_BRANCH=redwood-s-oss
KERNEL_CONFIG=vendor/redwood_GKI.config
KERNEL_IMAGE_NAME=Image.gz-dtb
ARCH=arm64
USE_CUSTOM_CLANG=true
USE_AOSP_CLANG=true
AOSP_CLANG_SYSTEM=linux-x86
AOSP_CLANG_BRANCH=master
AOSP_CLANG_VERSION=r450784e
KERNELSU_ENABLE=true
KERNELSU_VERSION=next
